ALTER TABLE users ADD COLUMN IF NOT EXISTS "e2eePublicKey" TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS "ciphertext" TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS "nonce" TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS "keyEpoch" INTEGER DEFAULT 1;

-- Ensure they are nullable for public context
ALTER TABLE messages ALTER COLUMN ciphertext DROP NOT NULL;
ALTER TABLE messages ALTER COLUMN nonce DROP NOT NULL;
ALTER TABLE messages ALTER COLUMN "keyEpoch" DROP NOT NULL;
